# Generated by Django 5.2.16 on 2026-07-27 09:19

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangocms_form_builder", "0007_captcha"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this webhook configuration",
                        max_length=255,
                        verbose_name="Configuration name",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        help_text="The webhook URL provided by your service (Make.com, Zapier, etc.)",
                        verbose_name="Webhook URL",
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("bearer", "Bearer token"),
                            ("api_key", "API key"),
                            ("basic", "Basic auth"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Authentication method",
                    ),
                ),
                (
                    "auth_token",
                    models.TextField(
                        blank=True,
                        help_text="Bearer token, API key, or base64 encoded credentials for basic auth",
                        verbose_name="Authentication token/key",
                    ),
                ),
                (
                    "auth_header_name",
                    models.CharField(
                        blank=True,
                        default="Authorization",
                        help_text='Header name for API key authentication. Use "x-make-apikey" for Make.com (ignored for bearer/basic auth).',
                        max_length=100,
                        verbose_name="Auth header name",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of retry attempts for failed submissions",
                        verbose_name="Maximum retries",
                    ),
                ),
                (
                    "retry_delay_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Initial delay between retry attempts (exponential backoff applied)",
                        verbose_name="Retry delay (seconds)",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="HTTP request timeout in seconds",
                        verbose_name="Request timeout (seconds)",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable this webhook configuration",
                        verbose_name="Active",
                    ),
                ),
                (
                    "include_user_data",
                    models.BooleanField(
                        default=True,
                        help_text="Include user information in the webhook payload",
                        verbose_name="Include user data",
                    ),
                ),
                (
                    "include_metadata",
                    models.BooleanField(
                        default=True,
                        help_text="Include request metadata (user agent, referer, etc.)",
                        verbose_name="Include metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Webhook configuration",
                "verbose_name_plural": "Webhook configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_name",
                    models.CharField(max_length=255, verbose_name="Form name"),
                ),
                (
                    "form_data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="The cleaned form data from the submission",
                        verbose_name="Form data",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="User agent, referer, IP address, etc.",
                        verbose_name="Request metadata",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retry_exhausted", "Retry exhausted"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry count"),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to attempt the next retry",
                        null=True,
                        verbose_name="Next retry at",
                    ),
                ),
                (
                    "last_response_status",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Last HTTP status"
                    ),
                ),
                (
                    "last_response_body",
                    models.TextField(blank=True, verbose_name="Last response body"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed at"
                    ),
                ),
                (
                    "form_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitting user",
                    ),
                ),
                (
                    "webhook_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangocms_form_builder.webhookconfiguration",
                        verbose_name="Webhook configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook submission",
                "verbose_name_plural": "Webhook submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_url", models.URLField(verbose_name="Request URL")),
                ("request_method", models.CharField(default="POST", max_length=10)),
                (
                    "request_headers",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Request headers",
                    ),
                ),
                (
                    "request_payload",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Request payload",
                    ),
                ),
                (
                    "response_status",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Response status"
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="Response headers",
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Response body"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (ms)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="djangocms_form_builder.webhooksubmission",
                        verbose_name="Webhook submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook log",
                "verbose_name_plural": "Webhook logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhooksubmission",
            index=models.Index(
                fields=["status", "next_retry_at"], name="webhook_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooksubmission",
            index=models.Index(
                fields=["form_name", "created_at"], name="webhook_form_name_idx"
            ),
        ),
    ]
